name: CodeCov
on: [workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate Report
      run: |
        pip install coverage
        cd gcastle
        coverage run -m unittest ./tests/test_all_castle.py
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
